### PR TITLE
walters quiz3

### PR DESCRIPTION
**Pull request by muirw5809**

### CODE REVIEW

**Comment by MrLamont-HHSS** [comment]
You have no analysis. Another issue, if(i = i+1) can never happen. When is i ever 1 more than i? Your while loop also has an incorrect condition. You are missing the gap condition. This means that your program may actually exit prematurely without sorting the array.

**Comment by muirw5809** [comment]
The analysis file was accidentally created in the wrong project so that's
why when I submitted it the file wasn't included, do you still want me to
submit it?

**Comment by muirw5809** [comment]
It won't let me make a pull request to you so I sent it through google docs

**Pull request closed without merging**
